name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Analyze
      run: cargo clippy -- -D warnings
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test

  cross_build:
    name: Cross Build - ${{ matrix.platform.os-name }}
    strategy:
      matrix:
        platform:
          - os-name: Linux-x86_64
            runs-on: ubuntu-24.04
            target: x86_64-unknown-linux-musl

          - os-name: Linux-aarch64
            runs-on: ubuntu-24.04
            target: aarch64-unknown-linux-musl

          - os-name: Windows-x86_64
            runs-on: windows-latest
            target: x86_64-pc-windows-msvc

          - os-name: macOS-x86_64
            runs-on: macOS-latest
            target: x86_64-apple-darwin

    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: ${{ matrix.platform.target }}
          args: "--release"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: zotex-${{ matrix.platform.target }}
          path: target/${{ matrix.platform.target }}/release/zotex${{ matrix.platform.target == 'x86_64-pc-windows-msvc' && '.exe' || '' }}
      
