name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions-rust-lang/setup-rust-toolchain@v1
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Analyze
      run: cargo clippy -- -D warnings
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test
      
