name: Release
on:
  push:
    tags: ['v*']

jobs:
  release:
    uses: xctions/xctions-rust-release/.github/workflows/rust-release.yml@54b47752a437ff4512eafbbed71bde5c3a9e4ef8
    with:
      release-tag: ${{ github.ref_name }}
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}